choco install wget /y
choco install 7zip /y
choco install dropbox /y
choco install skype /y
choco install javaruntime /y
choco install google-chrome-x64 /y
choco install firefox /y
choco install vagrant /y
choco install nodejs.install /y
choco install virtualbox /y
choco install intellijidea-ultimate /y
choco install slack /y
choco install googlejapaneseinput /y
choco install clover /y
choco install adobereader /y
choco install maven /y
choco install jdk8 /y
choco install eclipse /y
choco install emacs /y
choco install python2 /y
choco install r.project /y
choco install sudo /y
