choco install wget
choco install 7zip
choco install dropbox
choco install skype
choco install javaruntime
choco install google-chrome-x64
choco install firefox
choco install winrar
choco install vagrant
choco install nodejs.install
choco install virtualbox
choco install xyzzy
choco install intellijidea-ultimate
choco install slack
choco install googlejapaneseinput
choco install clover
choco install adobereader
choco install maven
choco install jdk8
choco install eclipse
choco install emacs
choco install python2
choco install pip
choco install easy.install
choco install r.project
choco install sudo